import { ClothingItem } from '../types/wardrobe';

/**
 * Realistic starter wardrobe data with high-res lookbook sample product images
 * so the app feels alive, tactile, and visually rich immediately.
 */
export const MOCK_CLOTHING: ClothingItem[] = [
  // ─── White Tees (school uniform staples) ────────────────────────────
  {
    id: '1a',
    name: 'White Uniqlo Tee #1',
    category: 'tops',
    color: 'White',
    brand: 'Uniqlo',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5448.png',
    isUniformWhiteTee: true,
    lastWornAt: '2026-09-13T08:00:00Z',
    notes: 'Airism crew neck',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: '1b',
    name: 'White Uniqlo Tee #2',
    category: 'tops',
    color: 'White',
    brand: 'Uniqlo',
    location: 'batangas_dorm',
    status: 'worn',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5438.png',
    isUniformWhiteTee: true,
    lastWornAt: '2026-09-14T08:00:00Z',
    notes: 'Airism crew neck',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: '1c',
    name: 'White Plain Tee #3',
    category: 'tops',
    color: 'White',
    brand: null,
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5448.png',
    isUniformWhiteTee: true,
    lastWornAt: null,
    notes: 'Backup at home',
    createdAt: '2026-07-15T00:00:00Z',
  },
  {
    id: '1d',
    name: 'White Uniqlo Tee #4',
    category: 'tops',
    color: 'White',
    brand: 'Uniqlo',
    location: 'batangas_dorm',
    status: 'in_laundry',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5438.png',
    isUniformWhiteTee: true,
    lastWornAt: '2026-09-12T08:00:00Z',
    notes: 'Airism crew neck, slight collar stain',
    createdAt: '2026-06-01T00:00:00Z',
  },

  // ─── Other Tops ─────────────────────────────────────────────────────
  {
    id: '2a',
    name: 'Black Carhartt Pocket Tee',
    category: 'tops',
    color: 'Black',
    brand: 'Carhartt WIP',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-10T18:00:00Z',
    notes: 'Heavyweight cotton, good for layering',
    createdAt: '2026-03-20T00:00:00Z',
  },
  {
    id: '2b',
    name: 'Navy Stripe Polo',
    category: 'tops',
    color: 'Navy',
    brand: 'Lacoste',
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/polo_shirt/polo_shirt_PNG8166.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-08-25T10:00:00Z',
    notes: 'Church outfit',
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: '2c',
    name: 'Gray Graphic Tee',
    category: 'tops',
    color: 'Gray',
    brand: 'H&M',
    location: 'in_transit_bag',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5454.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-14T16:00:00Z',
    notes: 'Packed for the weekend',
    createdAt: '2026-04-05T00:00:00Z',
  },
  {
    id: '2d',
    name: 'Olive Green Oversized Tee',
    category: 'tops',
    color: 'Olive',
    brand: 'Shein',
    location: 'batangas_dorm',
    status: 'worn',
    imageUrl: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-14T20:00:00Z',
    notes: 'Comfy sleep shirt',
    createdAt: '2026-05-12T00:00:00Z',
  },

  // ─── Bottoms ────────────────────────────────────────────────────────
  {
    id: '3a',
    name: 'Black Slim Jeans',
    category: 'bottoms',
    color: 'Black',
    brand: 'Levi\'s',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/jeans/jeans_PNG5771.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-11T08:00:00Z',
    notes: '512 slim taper',
    createdAt: '2026-02-14T00:00:00Z',
  },
  {
    id: '3b',
    name: 'Khaki Chinos',
    category: 'bottoms',
    color: 'Khaki',
    brand: 'Uniqlo',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/jeans/jeans_PNG5776.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-12T08:00:00Z',
    notes: 'School uniform approved',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: '3c',
    name: 'Gray Joggers',
    category: 'bottoms',
    color: 'Gray',
    brand: 'Nike',
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/jeans/jeans_PNG5760.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-08T14:00:00Z',
    notes: 'Tech Fleece',
    createdAt: '2026-04-20T00:00:00Z',
  },
  {
    id: '3d',
    name: 'Navy Cargo Shorts',
    category: 'bottoms',
    color: 'Navy',
    brand: 'Dickies',
    location: 'in_transit_bag',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/jeans/jeans_PNG5765.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-13T10:00:00Z',
    notes: 'Weekend beater',
    createdAt: '2026-05-01T00:00:00Z',
  },
  {
    id: '3e',
    name: 'Dark Blue Denim Shorts',
    category: 'bottoms',
    color: 'Blue',
    brand: null,
    location: 'batangas_dorm',
    status: 'in_laundry',
    imageUrl: 'https://pngimg.com/uploads/jeans/jeans_PNG5762.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-13T18:00:00Z',
    notes: '',
    createdAt: '2026-07-22T00:00:00Z',
  },

  // ─── Underwear ──────────────────────────────────────────────────────
  {
    id: '4a_und',
    name: 'Black Boxer Briefs #1',
    category: 'underwear',
    color: 'Black',
    brand: 'Bench',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&auto=format&fit=crop&q=80',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-12T08:00:00Z',
    notes: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '4b_und',
    name: 'Gray Boxer Briefs #2',
    category: 'underwear',
    color: 'Gray',
    brand: 'Bench',
    location: 'batangas_dorm',
    status: 'worn',
    imageUrl: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&auto=format&fit=crop&q=80',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-14T08:00:00Z',
    notes: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '4c_und',
    name: 'White Boxer Briefs #3',
    category: 'underwear',
    color: 'White',
    brand: 'Bench',
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&auto=format&fit=crop&q=80',
    isUniformWhiteTee: false,
    lastWornAt: null,
    notes: 'Reserve at home',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '4d_und',
    name: 'Navy Boxer Briefs #4',
    category: 'underwear',
    color: 'Navy',
    brand: 'Bench',
    location: 'batangas_dorm',
    status: 'in_laundry',
    imageUrl: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&auto=format&fit=crop&q=80',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-13T08:00:00Z',
    notes: '',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '4e_und',
    name: 'White Socks (3-pack) Set A',
    category: 'underwear',
    color: 'White',
    brand: 'Uniqlo',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?w=600&auto=format&fit=crop&q=80',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-12T08:00:00Z',
    notes: 'Ankle-cut',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: '4f_und',
    name: 'Black Socks (3-pack) Set B',
    category: 'underwear',
    color: 'Black',
    brand: 'Nike',
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?w=600&auto=format&fit=crop&q=80',
    isUniformWhiteTee: false,
    lastWornAt: '2026-08-30T08:00:00Z',
    notes: 'Crew length',
    createdAt: '2026-04-15T00:00:00Z',
  },

  // ─── Footwear ───────────────────────────────────────────────────────
  {
    id: '5a',
    name: 'Nike Air Force 1',
    category: 'footwear',
    color: 'White',
    brand: 'Nike',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5816.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-14T08:00:00Z',
    notes: 'Daily school shoes',
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: '5b',
    name: 'Black Slides',
    category: 'footwear',
    color: 'Black',
    brand: 'Adidas',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/running_shoes/running_shoes_PNG5815.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-14T20:00:00Z',
    notes: 'Dorm slippers',
    createdAt: '2026-03-10T00:00:00Z',
  },
  {
    id: '5c',
    name: 'Brown Leather Loafers',
    category: 'footwear',
    color: 'Brown',
    brand: 'Sperry',
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/boots/boots_PNG7790.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-08-15T10:00:00Z',
    notes: 'Church / formal',
    createdAt: '2025-12-25T00:00:00Z',
  },

  // ─── Outerwear ──────────────────────────────────────────────────────
  {
    id: '6a',
    name: 'Black Carhartt Hoodie',
    category: 'outerwear',
    color: 'Black',
    brand: 'Carhartt WIP',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/jacket/jacket_PNG8058.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-10T07:00:00Z',
    notes: 'For cold lecture halls',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: '6b',
    name: 'Navy Windbreaker',
    category: 'outerwear',
    color: 'Navy',
    brand: 'North Face',
    location: 'in_transit_bag',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/jacket/jacket_PNG8058.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-08T06:00:00Z',
    notes: 'Rain jacket, packed just in case',
    createdAt: '2026-02-28T00:00:00Z',
  },

  // ─── Accessories ────────────────────────────────────────────────────
  {
    id: '7_acc_bag',
    name: 'Canvas Backpack',
    category: 'accessories',
    color: 'Navy',
    brand: 'Fjallraven',
    location: 'in_transit_bag',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/backpack/backpack_PNG6353.png',
    isUniformWhiteTee: false,
    lastWornAt: null,
    notes: 'Commute bag',
    createdAt: '2026-05-15T00:00:00Z',
  },
  {
    id: '7a',
    name: 'Black Baseball Cap',
    category: 'accessories',
    color: 'Black',
    brand: 'New Era',
    location: 'batangas_dorm',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/cap/cap_PNG5680.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-09-13T14:00:00Z',
    notes: 'NY Yankees fitted',
    createdAt: '2026-05-20T00:00:00Z',
  },
  {
    id: '7b',
    name: 'Classic Sport Sunglasses',
    category: 'accessories',
    color: 'Black',
    brand: 'Ray-Ban',
    location: 'calamba_home',
    status: 'clean',
    imageUrl: 'https://pngimg.com/uploads/sunglasses/sunglasses_PNG46.png',
    isUniformWhiteTee: false,
    lastWornAt: '2026-08-15T10:00:00Z',
    notes: 'UV protection',
    createdAt: '2025-11-01T00:00:00Z',
  },
];
